name: Create new Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/lib/**'
      - '.github/workflows/release.yml'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v4

      - uses: TriPSs/conventional-changelog-action@v5
        with:
          version-file: "./package.json"
          github-token: ${{ secrets.github_token }}

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: npm login && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_REGISTRY: 'https://registry.npmjs.org'
